OSSFinder/Entities/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OSSFinder.Entities
{
    [DisplayColumn("Title")]
    public class Project : IEntity
    {
        public Project()
        {
            Authors = new HashSet<ProjectAuthor>();
            Listed = true;
        }

        public ProjectRegistration ProjectRegistration { get; set; }
        public int ProjectRegistrationKey { get; set; }

        [Obsolete("Will be removed in a future iteration, for now is write-only")]
        public virtual ICollection<ProjectAuthor> Authors { get; set; }

        public DateTime Created { get; set; }

        public virtual ICollection<ProjectDependency> Dependencies { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed but *IS* used for searches. Db column is nvarchar(max).
        /// </remarks>
        public string Description { get; set; }

        public int DownloadCount { get; set; }

        /// <remarks>
        /// Is not a property that we support. Maintained for legacy reasons.
        /// </remarks>
        [Obsolete]
        public string ExternalPackageUrl { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed and not used for searches. Db column is nvarchar(max).
        /// </remarks>
        public string IconUrl { get; set; }

        public bool IsLatest { get; set; }
        public bool IsLatestStable { get; set; }

        /// <summary>
        /// This is when the Package Entity was last touched (so caches can notice changes). In UTC.
        /// </summary>
        public DateTime LastUpdated { get; set; }

        /// <summary>
        /// This is when the Package Metadata was last edited by a user. Or NULL. In UTC.
        /// </summary>
        public DateTime? LastEdited { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed and not used for searches. Db column is nvarchar(max).
        /// </remarks>
        public string LicenseUrl { get; set; }

        public bool Listed { get; set; }

        public bool HideLicenseReport { get; set; }

        [StringLength(20)]
        public string Language { get; set; }

        public DateTime Published { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed and not used for searches. Db column is nvarchar(max).
        /// </remarks>
        public string ProjectUrl { get; set; }

        public bool RequiresLicenseAcceptance { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed and not used for searches. Db column is nvarchar(max).
        /// </remarks>
        public string Summary { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed and *IS* used for searches, but is maintained via Lucene. Db column is nvarchar(max).
        /// </remarks>
        public string Tags { get; set; }

        [StringLength(256)]
        public string Title { get; set; }

        public string FlattenedAuthors { get; set; }

        public int Key { get; set; }

        /// <summary>
        /// The logged in user when this package version was created.
        /// NULL for older packages.
        /// </summary>
        public User User { get; set; }
        public int? UserKey { get; set; }
    }
}

OSSFinder/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OSSFinder.Configuration;
using OSSFinder.Entities;
using OSSFinder.Infrastructure.Attributes;
using OSSFinder.Models.ViewModels;
using OSSFinder.Services.Interfaces;

namespace OSSFinder.Controllers
{
    public partial class ProjectsController : AppController
    {
        private readonly IAppConfiguration _config;
        private readonly IMessageService _messageService;
        private readonly IProjectService _projectService;
        private readonly IEntitiesContext _entitiesContext;
        private readonly ICacheService _cacheService;

        public ProjectsController(
            IProjectService projectService,
            IMessageService messageService,
            IEntitiesContext entitiesContext,
            IAppConfiguration config,
            ICacheService cacheService) 
        {
            _projectService = projectService;
            _messageService = messageService;
            _entitiesContext = entitiesContext;
            _config = config;
            _cacheService = cacheService;
        }

        public virtual ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [Route("project/new")]
        public virtual ActionResult New() 
        {
            return View("New_Step1", new NewProjectViewModel());
        }

        [Authorize]
        [Route("project/process_step_1")]
        public virtual ActionResult ProcessStep1(NewProjectViewModel model)
        {
            return new EmptyResult();
        }

        [Authorize]
        [Route("project/new_step2")]
        public virtual ActionResult NewStep2(NewProjectViewModel model)
        {
            if (model == null) {
                return RedirectToAction("New");
            }

            return View("New_Step2", model);
        }
    }
}

OSSFinder/Views/Projects/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

OSSFinder/Views/Projects/New_Step1.cshtml
@using OSSFinder.Infrastructure.Extensions
@model OSSFinder.Models.ViewModels.NewProjectStep1
@{
    ViewBag.Title = "Add a Project";
    Layout = "../Shared/_FocusedWizardLayout.cshtml";
}

<header class="aui-page-header">
    <div class="aui-page-header-inner">
        <div class="aui-page-header-main">
            <h1>Add a Project</h1>
        </div>
        <div class="aui-page-header-actions">
            <ol class="aui-progress-tracker aui-progress-tracker-inverted">
                <li class="aui-progress-tracker-step aui-progress-tracker-step-current"><a href="#1">Name and Description</a></li>
                <li class="aui-progress-tracker-step aui-progress-tracker-step-current"><span>Project Dependencies</span></li>
                <li class="aui-progress-tracker-step"><span>Project/Publish Settings</span></li>
            </ol>
        </div>
    </div>
</header>
<div class="aui-page-panel">
    <div class="aui-page-panel-inner">
        <section class="aui-page-panel-content">
            <h2>Name and Description</h2>
            
            @using (Html.BeginForm("ProcessStep1", "Projects", FormMethod.Post, new { @class = "aui" }))
            {
                @Html.AntiForgeryToken()

                <fieldset>
                    <div class="field-group">
                        @Html.LabelFor(m => m.RepositoryUrl)
                        @Html.TextBoxFor(m => m.RepositoryUrl, new { @class = "text" })
                        <div class="description">Eg. AT (for a project named Atlassian)</div>
                        @Html.ValidationMessageFor(m => m.RepositoryUrl)
                    </div>
                    
                    <div class="field-group">
                        @Html.LabelFor(m => m.Name)
                        @Html.TextBoxFor(m => m.Name, new { @class = "text" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                    
                    <div class="field-group">
                        @Html.LabelFor(m => m.Description)
                        @Html.TextAreaFor(m => m.Description, new { @class = "textarea long-field", @rows = 3 })
                        @Html.ValidationMessageFor(m => m.Description)
                    </div>
                    
                    <div class="field-group">
                        @Html.LabelFor(m => m.Language)
                        @Html.TextBoxFor(m => m.Language, new { @class = "text" })
                        @Html.ValidationMessageFor(m => m.Language)
                    </div>
                </fieldset>
                <div class="buttons-container">
                    <div class="buttons">
                        <input class="aui-button aui-button-primary" type="submit" id="submit" name="submit" value="Next">
                    </div>
                </div>
            }
        </section>
    </div>
</div>

OSSFinder/Views/Projects/New_Step2.cshtml
@model OSSFinder.Models.ViewModels.NewProjectViewModel
@{
    ViewBag.Title = "Add a Project";
    Layout = "../Shared/_FocusedWizardLayout.cshtml";
}

<header class="aui-page-header">
    <div class="aui-page-header-inner">
        <div class="aui-page-header-main">
            <h1>Add a Project</h1>
        </div>
        <div class="aui-page-header-actions">
            <ol class="aui-progress-tracker aui-progress-tracker-inverted">
                <li class="aui-progress-tracker-step"><span>Name and Description</span></li>
                <li class="aui-progress-tracker-step aui-progress-tracker-step-current"><a href="#1">Project Dependencies</a></li>
                <li class="aui-progress-tracker-step"><span>Project/Publish Settings</span></li>
            </ol>
        </div>
    </div>
</header>
<div class="aui-page-panel">
    <div class="aui-page-panel-inner">
        <section class="aui-page-panel-content">
            <h2>Project Dependencies</h2>
            
            @using (Html.BeginForm("ProcessStep1", "Projects", FormMethod.Post, new { @class = "aui" }))
            {
                @Html.AntiForgeryToken()

                <fieldset>
                    <div class="field-group">
                        @Html.LabelFor(m => m.RepositoryUrl)
                        @Html.TextBoxFor(m => m.RepositoryUrl, new { @class = "text" })
                        <div class="description">Enter in the repository URL for this project</div>
                        @Html.ValidationMessageFor(m => m.RepositoryUrl)
                    </div>
                    
                    <div class="field-group">
                        @Html.LabelFor(m => m.Name)
                        @Html.TextBoxFor(m => m.Name, new { @class = "text" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                    
                    <div class="field-group">
                        @Html.LabelFor(m => m.Description)
                        @Html.TextAreaFor(m => m.Description, new { @class = "textarea long-field", @rows = 3 })
                        @Html.ValidationMessageFor(m => m.Description)
                    </div>
                    
                    <div class="field-group">
                        @Html.LabelFor(m => m.Language)
                        @Html.TextBoxFor(m => m.Language, new { @class = "text" })
                        @Html.ValidationMessageFor(m => m.Language)
                    </div>
                </fieldset>
                <div class="buttons-container">
                    <div class="buttons">
                        <input class="aui-button aui-button-primary" type="submit" id="submit" name="submit" value="Next">
                    </div>
                </div>
            }
        </section>
    </div>
</div>